
spring:
  application:
    name: maotai

maotai:
  appId:
    xlth: wxded2e7e6d60ac09d # 新联惠购
    glyp: wx61549642d715f361 # 贵旅优品
    kglg: wx613ba8ea6a002aa8 # 空港乐购
    hlqg: wx936aa5357931e226 # 航旅黔购
    zhcs: wx624149b74233c99a # 遵航出山
    gyqp: wx5508e31ffe9366b8 # 贵盐黔品
    llsc: wx821fb4d8604ed4d6 # 乐旅商城
    ylqx: wxee0ce83ab4b26f9c # 驿路黔寻
  cookies:
    xlth: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDA4ODcwMzc4IiwiaXNzIjoiZ21hbGwtc3RhcnNreSIsImxvZ0lkIjoibnVsbCIsImV4cCI6MTcyNTI3NDkyOCwiaWF0IjoxNzE3NDk4OTI4fQ.1EOYtDTLDU9CaaStteAwMxaaIYFW_sSOnp6Dk1P_JGY # 新联惠购
    glyp: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDA4ODcwOTAyIiwiaXNzIjoiZ21hbGwtc3RhcnNreSIsImxvZ0lkIjoibnVsbCIsImV4cCI6MTcyNTI3NDkzMSwiaWF0IjoxNzE3NDk4OTMxfQ.wnSBsRZ2vPvwCsWouJthynI5bOfmlnDOSJx6SBYxvAs # 贵旅优品
    kglg: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDA4ODcxMzUyIiwiaXNzIjoiZ21hbGwtc3RhcnNreSIsImxvZ0lkIjoibnVsbCIsImV4cCI6MTcyNTI3NDkzMSwiaWF0IjoxNzE3NDk4OTMxfQ.PJuR_HrMQk3PR2Aze4wYoJrNMejswqyu9xhmi-7vP_A # 空港乐购
    hlqg: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDA4ODczMDIyIiwiaXNzIjoiZ21hbGwtc3RhcnNreSIsImxvZ0lkIjoibnVsbCIsImV4cCI6MTcyNTI3NDkyOSwiaWF0IjoxNzE3NDk4OTI5fQ.viJfw7LxhaRNnrrbaKgtrQ0Ityp4eVGSTNclJYvZvok # 航旅黔购
    zhcs: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDA4ODcyMDk1IiwiaXNzIjoiZ21hbGwtc3RhcnNreSIsImxvZ0lkIjoibnVsbCIsImV4cCI6MTcyNTI3NDkzMCwiaWF0IjoxNzE3NDk4OTMwfQ.79BG6rJNSPEm-4d60_i5_4evwTziIXYPekFaESTz-Ps # 遵航出山
    gyqp: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDA4ODcxNjkyIiwiaXNzIjoiZ21hbGwtc3RhcnNreSIsImxvZ0lkIjoibnVsbCIsImV4cCI6MTcyNTI3NDkyOSwiaWF0IjoxNzE3NDk4OTI5fQ.VOVZt4JAmJyYfJ3AFRr4eoWUWGyJE_qvFNEBY7q-MqY # 贵盐黔品
    llsc: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDA4ODcyNDg4IiwiaXNzIjoiZ21hbGwtc3RhcnNreSIsImxvZ0lkIjoibnVsbCIsImV4cCI6MTcyNTI3NDkyNywiaWF0IjoxNzE3NDk4OTI3fQ.dkaigpS17Bx-R58A1EW1cyv7BFqKfdUKParJeM_C3Qk # 乐旅商城
    ylqx: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDI3MTMyOTQ4IiwiaXNzIjoiZ21hbGwtc3RhcnNreSIsImxvZ0lkIjoibnVsbCIsImV4cCI6MTcyNTI3NDkzMiwiaWF0IjoxNzE3NDk4OTMyfQ.nlv8DaENRwhE8jz42QMSPwelE6p4YiLy7EC1F1KqObA # 驿路黔寻
  reserve:
    scheduled:
      cron: 0 45 8 * * * # 预约定时
      enable: true # 是否开启
  message:
    pushKey: PDU
    pushUrl: https://api2.pushdeer.com/message/push
    scheduled:
      cron: 0 45 10 * * * # 中奖记录定时
      enable: true # 是否开启
  msg:
    token: 624e7c0cc96e4cc7a4435d4dc513e3fc
    
async:
  executor:
    thread:
      # 配置核心线程数
      core_pool_size: 10
      # 配置最大线程数
      max_pool_size: 20
      # 配置队列大小
      queue_capacity: 999
      name:
        prefix: async-service-