
spring:
  application:
    name: maotai

maotai:
  appId:
    xlth: wxded2e7e6d60ac09d # 新联惠购
    glyp: wx61549642d715f361 # 贵旅优品
    kglg: wx613ba8ea6a002aa8 # 空港乐购
    hlqg: wx936aa5357931e226 # 航旅黔购
    zhcs: wx624149b74233c99a # 遵航出山
    gyqp: wx5508e31ffe9366b8 # 贵盐黔品
    llsc: wx821fb4d8604ed4d6 # 乐旅商城
    ylqx: wxee0ce83ab4b26f9c # 驿路黔寻
  cookies:
    xlth: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDA4ODcwMzc4IiwiaXNzIjoiZ21hbGwtc3RhcnNreSIsImxvZ0lkIjoibnVsbCIsImV4cCI6MTcyNTAwNzIzOSwiaWF0IjoxNzE3MjMxMjM5fQ.EiQHz0sS6uGMldrtu6yGDxFhIz5UfZKcEx0CTrAFCpI # 新联惠购
    glyp: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDA4ODcwOTAyIiwiaXNzIjoiZ21hbGwtc3RhcnNreSIsImxvZ0lkIjoibnVsbCIsImV4cCI6MTcyNTAwNzI0MywiaWF0IjoxNzE3MjMxMjQzfQ.i9zUHxfYoGwrPGKI_DTC0ejqktOV3KVjV2FqLCpyHLc # 贵旅优品
    kglg: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDA4ODcxMzUyIiwiaXNzIjoiZ21hbGwtc3RhcnNreSIsImxvZ0lkIjoibnVsbCIsImV4cCI6MTcyNTAwNzI0MiwiaWF0IjoxNzE3MjMxMjQyfQ._lvYMfiWMmPO2uE2dBy749343p4QZi_-I7qR75mUkcw # 空港乐购
    hlqg: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDA4ODczMDIyIiwiaXNzIjoiZ21hbGwtc3RhcnNreSIsImxvZ0lkIjoibnVsbCIsImV4cCI6MTcyNTAwNzI0MCwiaWF0IjoxNzE3MjMxMjQwfQ.R2duO6MjHdFwRz-dIfZh8zgXX_GydyLyEqvnbWesCEM # 航旅黔购
    zhcs: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDA4ODcyMDk1IiwiaXNzIjoiZ21hbGwtc3RhcnNreSIsImxvZ0lkIjoibnVsbCIsImV4cCI6MTcyNTAwNzI0MSwiaWF0IjoxNzE3MjMxMjQxfQ.bkW-_jwn_HRqWF2zUcuvV9fTa6v3nbqz4yhOuax8WEE # 遵航出山
    gyqp: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDA4ODcxNjkyIiwiaXNzIjoiZ21hbGwtc3RhcnNreSIsImxvZ0lkIjoibnVsbCIsImV4cCI6MTcyNTAwNzI0MCwiaWF0IjoxNzE3MjMxMjQwfQ.ZeEomQ4QBu2Mpw3KouU-KWdnLbbGVikWRrsLrKg01WM # 贵盐黔品
    llsc: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDA4ODcyNDg4IiwiaXNzIjoiZ21hbGwtc3RhcnNreSIsImxvZ0lkIjoibnVsbCIsImV4cCI6MTcyNTAwNzIzOCwiaWF0IjoxNzE3MjMxMjM4fQ.aJ0hSzVmXGrcW9rq6TJuUYKrhKhPK3hri6_t9c-J75Y # 乐旅商城
    ylqx: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDI3MTMyOTQ4IiwiaXNzIjoiZ21hbGwtc3RhcnNreSIsImxvZ0lkIjoibnVsbCIsImV4cCI6MTcyNTAwNzI0NCwiaWF0IjoxNzE3MjMxMjQ0fQ.zzkfZ4uiIl-IpxZ59NtoaOMbpS0Ne8klmDFCwJnmQ9E # 驿路黔寻
  reserve:
    scheduled:
      cron: 0 45 8 * * * # 预约定时
      enable: true # 是否开启
  message:
    pushKey: PDU
    pushUrl: https://api2.pushdeer.com/message/push
    scheduled:
      cron: 0 45 10 * * * # 中奖记录定时
      enable: true # 是否开启
  msg:
    token: 624e7c0cc96e4cc7a4435d4dc513e3fc